name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      run: make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: make artifact
          path: build
